/**
 * @fileoverview Miscellaneous utility functions.
 * @author alvin@omgimanerd.tech (Alvin Lin)
 */

var colors = require('colors');

module.exports.defaultJoin = function(dataList) {
  return dataList.join('\n').trim() || 'none';
};

/**
 * Because we don't like the unhelpful error messages generated by commander
 * when a required argument isn't specified, we set all arguments as optional
 * and use this check instead to print the help message specific to that
 * command.
 * @param {Object} argument The argument to check
 * @param {function()} help The help function to run if the argument check
 *   failed.
 */
module.exports.ensureArgument = function(argument, help) {
  if (typeof(argument) !== 'string' || argument === '[object Object]') {
    help();
  }
};

module.exports.handleError = function(error) {
  if (error) {
    console.log(error.message.red);
    process.exit(1);
  }
};

module.exports.parseStatus = function(status) {
  switch (status) {
    case 'new':
    case 'off':
      return status.red;
      break;
    case 'active':
      return status.green;
      break;
    case 'archived':
      return status.blue;
      break;
  }
};
